### PR TITLE
add desktop and eye icon

### PR DESCRIPTION
**Pull request by christieb7007**

### CODE REVIEW

**Comment by robmcguinness** [comment]
do the docs need  updating?

**Comment by derekonay** [comment]
@christieb7007 @robmcguinness Both of the icons that you added here plus some others that Teresa had asked me about (download, etc) are already in v1 tag 1.2.6. Would it just make sense to pull over the font file from that tag so that all the icons are up to date?

**Comment by christieb7007** [comment]
We are trying to keep the icon package small and add icons as we need them (several were removed in v3 for this reason).
Will update to add icons to the docs

**Comment by TheSharpieOne** [comment]
I believe this change shifted the "text" value of the icons so that the inline-help is showing the wrong icon:
https://github.com/Availity/availity-uikit/blob/741dbb7d3b1435df0cf611d887980b493ce6bf27/packages/uikit/scss/_help.scss#L1-L6

It used `\e81b` which was `help-circle` before this change and is now `filter`

**Pull request merged**
