### PR TITLE
Look & feel update for vertical wizards

### PR DESCRIPTION
**Pull request by ivern**

### CODE REVIEW

**Comment by JamieCrisman** [comment]
Screenshots of the changes

newwizard-vertical

newwizard-horizontal

**Comment by robmcguinness** [comment]
the only problem i see is that this would break current wizard users.   what about adding this as a modifier to the current wizard styles instead so they both can coexist? something like `wizard-progress`?

**Comment by taylornturner** [comment]
Hello all. The screenshots posted above seem to reflect the current UI Kit step tracker. Changes should appear as per the confluence page. https://confluence.availity.com/pages/viewpage.action?pageId=51349398
See the Open Step Tracker for changes. Please let me know if you have any questions.

Rob.. I don't mind making the open wizard a separate style. It would be nice to update the current style to look like the Closed Step Tracker in the confluence page attached.

Thanks.

**Comment by JamieCrisman** [comment]
Alright, so Taylor requested some changes to the documentation so that it will demonstrate both UX methods.

### Horizontal Open step

horiz-unnumbered

### Horizontal Linear

horiz-numbered

### Vertical Open step

vert-unnumbered
### Vertical Linear

vert-numbered

**Comment by taylornturner** [comment]
Hello James,

The functionality looks right. Would it be too much to ask you to change both the green borders and the green circle backgrounds to be #009a57 instead of the #02a17c? Additionally, the active text should also be #009a57 at a weight of 500 to further emphasize the active step.

Thanks so much,

Taylor Turner
UI Designer
Availity | 740 E Campbell Rd. Suite #1000 Richardson, TX
P 972.383.6448 | C 281.203.1137
taylor.turner@availity.com<mailto:taylor.turner@availity.com>

[00 AV Logo RGB]

The information contained in this e-mail may be privileged and confidential under applicable law. It is intended solely for the use of the person or firm named above. If the reader of this e-mail is not the intended recipient, please notify us immediately by returning the e-mail to the originating e-mail address. Availity, LLC is not responsible for errors or omissions in this e-mail message. Any personal comments made in this e-mail do not reflect the views of Availity, LLC.

**Comment by JamieCrisman** [comment]
Still have issues with 500 weight not showing up.

there's an issue with badges without text not lining up... half works by inserting `&nbsp;`

**Pull request merged**
