### PR TITLE
Update availity-anthem.less

### PR DESCRIPTION
**Pull request by jsarman**
Remove referenced to a previously removed image file.

### CODE REVIEW

**Comment by jsarman** [comment]
Closing this pull request and will create one with updated dist files and version bumped.

**Comment by bobbennett** [comment]
You actually don't need to update the dist files or bump the version in your pull request. We do both of those things when we create a release. I would reopen this one and close the other.

**Comment by jsarman** [comment]
Thx

**Comment by jsarman** [comment]
Reopening without the bump and dist build

**Pull request merged**
